#  Этот файл был сгенерирован тНавигатор v23.4-5689-g1082f6c.
#  Copyright (C) Рок Флоу Динамикс 2005-2024.
#  Все права защищены.

# This file is MACHINE GENERATED! Do not edit.

#api_version=v0_0_117

from __main__.tnav.workflow import *
from tnav_debug_utilities import *
from datetime import datetime, timedelta


declare_workflow (workflow_name="Sg",
      variables=[])


Sg_variables = {

}

def Sg (variables = Sg_variables):
    pass
    check_launch_method ()


    begin_user_imports ()
    end_user_imports ()

    begin_wf_item (index = 1)
    create_blocked_well_log_by_property (mesh=find_object (name="SHORT_AREA (Dynamic Model)",
          type="gt_tnav_grid_3d_data"),
          result_grid_property=find_object (name="SGAS",
          type="gt_tnav_cube_3d_data"),
          BlockedWells=find_object (name="Sgas",
          type="BlockedWells"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          clear_all_values=True)
    end_wf_item (index = 1)


    begin_wf_item (index = 2)
    wells_log_create_by_blocked_wells (mesh=find_object (name="SHORT_AREA (Dynamic Model)",
          type="gt_tnav_grid_3d_data"),
          blocked_wells=find_object (name="Sgas",
          type="BlockedWells"),
          log_step_type="set_log_step",
          log_step_val=0.1,
          source_log=find_object (name="AHF10",
          type="WellLog"),
          result_log=find_object (name="Sg_gdm",
          type="WellLog"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          use_filter=False,
          user_cut=find_object (name="DX",
          type="gt_tnav_cube_3d_data"),
          comparator=Comparator (rule="not_equals",
          value=0),
          clear_existing_data=False)
    end_wf_item (index = 2)


    begin_wf_item (index = 3)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_rigis_Ach3",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Кг_ГИС",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach3_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach3_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 3)


    begin_wf_item (index = 4)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_rigis_Ach4",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Кг_ГИС",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach4_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach4_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 4)


    begin_wf_item (index = 5)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_rigis_Ach5",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Кг_ГИС",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach51_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach523_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 5)


    begin_wf_item (index = 6)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_gdm_Ach3",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Sg_gdm",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach3_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach3_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 6)


    begin_wf_item (index = 7)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_gdm_Ach4",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Sg_gdm",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach4_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach4_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 7)


    begin_wf_item (index = 8)
    wells_attribute_create_by_averaging_wells_log (result_well_attribute=find_object (name="Sg_gdm_Ach5",
          type="WellAttribute"),
          well_attribute_depth="middle_point",
          use_calculate_single_type=False,
          calculate_single_type="weighted",
          well_log=find_object (name="Sg_gdm",
          type="WellLog"),
          use_current_marker_set=False,
          current_marker_set=find_object (name="Default Set",
          type="MarkerSet"),
          marker_top=find_object (name="Ach51_top",
          type="WellMarker"),
          marker_bottom=find_object (name="Ach523_bot",
          type="WellMarker"),
          use_marker_unconformity=False,
          marker_unconformity=find_object (name="Top_Ach31_tnng17",
          type="WellMarker"),
          use_well_filter=False,
          well_filter=find_object (name="AchDev",
          type="WellFilter"),
          wells=find_object (name="Wells",
          type="gt_wells_entity"),
          trajectories=find_object (name="Trajectories",
          type="Trajectories"),
          use_override_discreteness=True,
          override_discreteness="Continuous",
          scale_type="TVDSS",
          continuous_averaging_method="Arithmetic",
          discrete_averaging_method="Thickness",
          facies_code=1,
          use_min_cut_value=True,
          min_cut_value=0.05,
          use_max_cut_value=False,
          max_cut_value=1,
          cutoff_type="Ignore values",
          use_cut_log=True,
          cut_log=find_object (name="LOB",
          type="WellLog"),
          use_no_log_value=False,
          no_log_value=0,
          use_no_marker_mode=False,
          no_marker_mode="set_zero_value",
          layer_parameters=False,
          discrete_well_log=find_object (name="LOB",
          type="WellLog"),
          code_value=0,
          discrete_log_mode="filter")
    end_wf_item (index = 8)


